# Generated by Django 4.2.3 on 2023-07-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='LinkMapping',
        ),
    ]
